apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-0qi0
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci10t-786-0001-tenant/ci10t-786-0001-app/devfile-sample-0qi0@sha256:7825302de53f8f4e14ea052c1e7dca81948a317d6874ce1490659bd5b36157d4
        name: my-nodejs
        resources: {}
status: {}
