apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-0qi0
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-0qi0
    app.kubernetes.io/part-of: ci10t-786-0001-app
  name: devfile-sample-0qi0
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-0qi0
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-0qi0
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci10t-786-0001-tenant/ci10t-786-0001-app/devfile-sample-0qi0@sha256:7825302de53f8f4e14ea052c1e7dca81948a317d6874ce1490659bd5b36157d4
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
